baseurl = "https://buelbuel73.github.io/verso-it-web/"
# baseurl = "/"
title = "Verso IT Solutions"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Mister B"
  bio = "Mister B's true identity is unknown. Maybe he is a successful White Hat or a Hacker. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  description = "Mister B's site about everything" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]

[Params.logo]
  subtitle = "... for a secure Infrastructure" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = false   # Configure layout for single pages
  # Enable widgets in given order
    widgets = ["search", "recent", "categories", "taglist", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  linkedin = "username"
  telegram = "username"
  github = "buelbuel73"
  gitlab = "username"
  bitbucket = "username"
  email = "example@example.com"